//: [Previous](@previous)

import Foundation

var greeting = "Hello, playground"

//: [Next](@next)

//Suppose you are given two strings s and t. String t is generated by random shuffling string s and then adding one more letter at a random position.
//Return the letter that was added to t.


func addedChar(s:String, t: String)->Character{
    let sChars = Array(s)
    let tChars = Array(t)
    for char in tChars{

        if sChars.filter({$0 == char}).count != tChars.filter({$0 == char}).count{
            return char
        }
    }

    var result: Character = Character (" ")
    return result
}

//let result = addedChar(s: "abcd", t: "ceadb")
let result = addedChar(s:"abbdd", t: "dabadb")
//let result = addedChar(s: "", t: "y")
//let result = addedChar(s: "aaaa", t: "aabaa")
//let result = addedChar(s: "ae", t: "aae")
print("Char is :",result)
